[package]
name = "biodiff"
description = "Compare binary files using sequence alignment"
repository = "https://www.github.com/8051Enthusiast/biodiff"
version = "1.0.3"
authors = ["8051Enthusiast <8051Enthusiast@protonmail.com>"]
edition = "2021"
license = "MIT"
default-run = "biodiff"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
	"hexagex",
]

[dependencies]
bio = "0.41.0"
crossterm = "0.24.0"
crossbeam-utils = "0.8.10"
cursive_buffered_backend = "0.6.0"
unicode-width = "0.1.9"
memmap2 = "0.5.5"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
dirs = "4.0.0"
regex = "1.6.0"
hexagex = { path = "hexagex", version = "0.2.0" }
realfft = "3.0.0"
num_cpus = "1.13.1"

[dependencies.cursive]
version = "0.19.0"
default-features = false
features = ["crossterm-backend"]
