[package]
name = "biodiff"
description = "Compare binary files using sequence alignment"
repository = "https://www.github.com/8051Enthusiast/biodiff"
version = "0.2.1"
authors = ["8051Enthusiast <8051Enthusiast@protonmail.com>"]
edition = "2018"
license = "MIT"
default-run = "biodiff"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
	"hexagex",
]

[dependencies]
bio = "0.39.1"
crossterm = "0.22.1"
crossbeam-utils = "0.8.6"
cursive_buffered_backend = "0.6.0"
unicode-width = "0.1.9"
memmap2 = "0.5.2"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
dirs = "4.0.0"

[dependencies.cursive]
version = "0.17.0"
default-features = false
features = ["crossterm-backend"]
