[package]
name = "biodiff"
description = "Compare binary files using sequence alignment"
repository = "https://www.github.com/8051Enthusiast/biodiff"
version = "0.2.0"
authors = ["8051Enthusiast <8051Enthusiast@protonmail.com>"]
edition = "2018"
license = "MIT"
default-run = "biodiff"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "0.34"
crossterm = "0.19"
crossbeam-utils = "0.8"
cursive_buffered_backend = "0.5"
unicode-width = "0.1"
memmap2 = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "3.0"

[dependencies.cursive]
version = "0.16"
default-features = false
features = ["crossterm-backend"]
