[package]
name = "biodiff-wfa2-sys"
version = "2.3.4"
edition = "2021"
links = "wfa2"

[features]
default = ["bundle_wfa2"]
bundle_wfa2 = []

[build-dependencies]
cmake = { version = "0.1" }
bindgen = "0.69.4"
