---
name: Build
on:
  push:
    tags:
      - v[0-9]+.*
jobs:
  build:
    name: Build Binary
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: "macos"
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: "linux"
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            suffix: "windows"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo test --target="${{ matrix.target }}" --release
          cargo build --target="${{ matrix.target }}" --release
      - run: |
          cargo install cargo-strip
          cargo strip --target="${{ matrix.target }}"
      - uses: actions/upload-artifact@v4
        if: matrix.os != 'windows-latest'
        with:
          name: 'biodiff-${{ matrix.suffix }}-${{ github.ref_name }}'
          path: |
            target/${{ matrix.target }}/release/biodiff
            target/${{ matrix.target }}/release/git-biodiff
      - uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest'
        with:
          name: 'biodiff-${{ matrix.suffix }}-${{ github.ref_name }}'
          path: |
            target/${{ matrix.target }}/release/biodiff.exe
            target/${{ matrix.target }}/release/git-biodiff.exe
