---
name: Build
on:
  push:
    tags:
      - v[0-9]+.*
jobs:
  build:
    name: Build Binary
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: "macos"
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: "linux"
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: "windows"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: |
          cargo test --release
          cargo build --release
      - run: |
          cargo install cargo-strip
          cargo strip
      - uses: actions/upload-artifact@v2
        if: matrix.os != 'windows-latest'
        with:
          name: 'biodiff-${{ matrix.suffix }}-${{ github.ref_name }}'
          path: |
            target/release/biodiff
            target/release/git-biodiff
      - uses: actions/upload-artifact@v2
        if: matrix.os == 'windows-latest'
        with:
          name: 'biodiff-${{ matrix.suffix }}-${{ github.ref_name }}'
          path: |
            target/release/biodiff.exe
            target/release/git-biodiff.exe
